name: Pipeline for customer environment
on:
  workflow_dispatch:

jobs: 
  call-reusable-workflow-siema-app:
    uses: ./.github/workflows/app1_image_builder_workflow.yml
    with:
      gh_environment: CUSTOMER_1
      DEPLOYMENT: customer

  call-reusable-workflow-siema-frontend:
    uses: ./.github/workflows/app2_image_builder_workflow.yml
    with:
      gh_environment: CUSTOMER_1
      DEPLOYMENT: customer