name: Pipeline for production environment
on:
  push:
    tags: ['v*.*.*']

jobs: 
  changes:
    runs-on: ubuntu-latest
    outputs:
      siema-app: ${{ steps.filter.outputs.siema-app }}
      siema-frontend: ${{ steps.filter.outputs.siema-frontend }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get previous tag to compare
      id: fetch_tag
      run: |
        git describe --tags --abbrev=0 HEAD~1
        echo "prev_tag=$(git describe --tags --abbrev=0 HEAD~1)" >> $GITHUB_OUTPUT